import Head from "next/head";

import { IndexPage } from "../components";
import { homePagePropTypes } from "../components/helpers/propTypes";

const examples = [
  {
    title: "Еда и напитки",
    author: "Константин",
    image: "/examples/example-1.jpg",
  },
  {
    title: "Ювелирные изделия",
    author: "Анна Смирнова",
    image: "/examples/example-2.jpg",
  },
  {
    title: "Косметика",
    author: "Михаил",
    image: "/examples/example-3.jpg",
  },
  {
    title: "Красота и здоровье",
    author: "Вениамин",
    image: "/examples/example-4.jpg",
  },
  {
    title: "Дом и дача",
    author: "Иван Петров",
    image: "/examples/example-5.jpg",
  },
];

const shortFeatures = [
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
];

export default function Home({ examples, shortFeatures }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexPage shortFeatures={shortFeatures} examples={examples} />
    </>
  );
}

Home.propTypes = homePagePropTypes;
Home.defaultProps = {
  examples: [],
  shortFeatures: [],
};

export async function getStaticProps() {
  return {
    props: {
      examples,
      shortFeatures,
    },
  };
}
