import Head from "next/head";

import { IndexPage } from "../components";
import { homePagePropTypes } from "../components/helpers/propTypes";

const examples = [
  {
    title: "Еда и напитки",
    author: "Константин",
    image: "/examples/example-1.jpg",
  },
  {
    title: "Ювелирные изделия",
    author: "Анна Смирнова",
    image: "/examples/example-2.jpg",
  },
  {
    title: "Косметика",
    author: "Михаил",
    image: "/examples/example-3.jpg",
  },
  {
    title: "Красота и здоровье",
    author: "Вениамин",
    image: "/examples/example-4.jpg",
  },
  {
    title: "Дом и дача",
    author: "Иван Петров",
    image: "/examples/example-5.jpg",
  },
];

const shortFeatures = [
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
  {
    title: "Начать бизнес в Интернете",
    description:
      "Создайте бизнес независимо от того, есть ли у вас свежая идея или вы ищете новый способ заработка. ",
    iconId: "trophy",
  },
];

const features = [
  {
    title: "С вами, куда бы вы ни пошли",
    description:
      "Используйте единую платформу для продажи продуктов кому угодно и где угодно - лично в торговой точке или онлайн через свой веб-сайт, социальные сети и онлайн-магазины.",
    imageSrc: "/features/feature-1.jpg",
    linkText: "Изучите способы продажи",
    linkPath: "#",
  },
  {
    title: "Анализируйте свой бизнес",
    description:
      "Избавьтесь от догадок в маркетинге с помощью встроенных инструментов, которые помогут вам создавать, проводить и анализировать кампании цифрового маркетинга.",
    imageSrc: "/features/feature-2.jpg",
    linkText: "Узнайте, как продвигать свой бизнес",
    linkPath: "#",
  },
  {
    title: "Управляйте всем",
    description:
      "Получите информацию, необходимую для роста - используйте единую панель управления для управления заказами, доставкой и платежами в любом месте.",
    imageSrc: "/features/feature-3.jpg",
    linkText: "Узнайте, как управлять своим бизнесом",
    linkPath: "#",
  },
];

const partners = [
  {
    name: "Cee Cee's Closet",
    image: "/partners/partner-1.jpg",
  },
  {
    name: "Nalata | Nalata",
    image: "/partners/partner-2.jpg",
  },
  {
    name: "Kirrin Finch",
    image: "/partners/partner-3.jpg",
  },
  {
    name: "Weso goods",
    image: "/partners/partner-4.jpg",
  },
  {
    name: "Coco and breezy",
    image: "/partners/partner-5.jpg",
  },
  {
    name: "Brooklyn Museum",
    image: "/partners/partner-6.jpg",
  },
  {
    name: "Adore me",
    image: "/partners/partner-7.jpg",
  },
];

export default function Home({ examples, features, shortFeatures, partners }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexPage
        partners={partners}
        shortFeatures={shortFeatures}
        features={features}
        examples={examples}
      />
    </>
  );
}

Home.propTypes = homePagePropTypes;
Home.defaultProps = {
  examples: [],
  features: [],
  shortFeatures: [],
};

export async function getStaticProps() {
  return {
    props: {
      examples,
      features,
      partners,
      shortFeatures,
    },
  };
}
